version: '3.4'

services:
  chc.presentation:
    image: ${DOCKER_REGISTRY-}chcpresentation
    build:
      context: .
      dockerfile: CHC.Presentation/Dockerfile
  
  postgres-service:
    container_name: postgres-chc
    image: postgres
    environment:
      POSTGRES_DB: chc
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
      - ./postgres-chc:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped